service: crud-amazon-dynamodb-aws

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  memorySize: 512
  timeout: 10
  environment: ${file(./serverless_ssm.yml)}
  apiGateway:
    apiKeys:
      - name: xApiKey
        value: ${file(./serverless_ssm.yml):X_API_KEY}
  logs:
    # Enable REST API logs
    restApi:
      accessLogging: true
      format: "requestId: $context.requestId"
      executionLogging: true
      level: INFO
      fullExecutionData: true
      role: arn:aws:iam::xxxx:role
      roleManagedExternally: false

plugins:
  - serverless-dynamodb-local
  - serverless-esbuild
  - serverless-offline-ssm
  - serverless-offline

functions:
  createPayment:
    handler: src/functions/createPayment.handler
    description: Function to create a payment object in the payments table
    timeout: 10
    events:
      - http:
          method: POST
          path: /${file(./serverless_ssm.yml):API_VERSION}/${file(./serverless_ssm.yml):API_ENDPOINT_PAYMENTS_NAME}/
          private: true 
  getAllPayments:
    handler: src/functions/getAllPayments.handler
    description: Function to get all payments object from the payments table db
    timeout: 10
    events:
      - http:
          method: GET
          path: /${file(./serverless_ssm.yml):API_VERSION}/${file(./serverless_ssm.yml):API_ENDPOINT_PAYMENTS_NAME}/list
          private: true
  getByUuidPayment:
    handler: src/functions/getByUuidPayment.handler
    description: Function to get a payments object by uuid from the payments table db
    timeout: 10
    events:
      - http:
          method: GET
          path: /${file(./serverless_ssm.yml):API_VERSION}/${file(./serverless_ssm.yml):API_ENDPOINT_PAYMENTS_NAME}/{uuid}
          private: true            
  updatePayment:
    handler: src/functions/updatePayment.handler
    description: Function to update a payment object from the payments table db
    timeout: 10
    events:
      - http:
          method: PUT
          path: /${file(./serverless_ssm.yml):API_VERSION}/${file(./serverless_ssm.yml):API_ENDPOINT_PAYMENTS_NAME}/{uuid}
          private: true           
resources:
  - ${file(src/resources/dynamo-payments-table.yml)}
custom:
  serverless-offline-ssm:
    stages:
      - dev
    ssm: ${file(./serverless_ssm.yml)}
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4002 
  dynamodb:
    stages:
      - dev
    start:
      inMemory: true
      migrate: true
      seed: true
      port: 8000
