service: microservice-mercadolibre-products-aws

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  memorySize: 512
  timeout: 10
  environment: ${file(./serverless_ssm.yml)}
  apiGateway:
    apiKeys:
      - name: xApiKey
        value: ${file(./serverless_ssm.yml):X_API_KEY}
  logs:
    # Enable REST API logs
    restApi:
      accessLogging: true
      format: "requestId: $context.requestId"
      executionLogging: true
      level: INFO
      fullExecutionData: true
      role: arn:aws:iam::xxxx:role
      roleManagedExternally: false

plugins:
  - serverless-dynamodb-local
  - serverless-esbuild
  - serverless-offline-ssm
  - serverless-offline

functions:
  hello:
    handler: src/functions/hello/handler.ts
    events:
      - http:
          path: /test
          method: POST
          private: true  

resources:
  
custom:
  serverless-offline-ssm:
    stages:
      - dev
    ssm: ${file(./serverless_ssm.yml)}
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4002 
